import { Doc, type Doc as DocT } from "../fmd/schema";
import typeASentence from "../../fixtures/showcase/s01-type-a-sentence.fmd.json";
import solstice from "../../fixtures/showcase/s02-solstice.fmd.json";

/**
 * Full showcase reels built with Fusion Motion (generated by fixtures/showcase/build.mjs).
 * `make()` returns a fresh, schema-complete copy, so opening one never mutates the source.
 */
export interface Example {
  id: string;
  title: string;
  blurb: string;
  tags: string[];
  make: () => DocT;
}

const load = (raw: unknown, name: string) => () => ({ ...Doc.parse(structuredClone(raw)), name });

export const EXAMPLES: Example[] = [
  {
    id: "type-a-sentence",
    title: "Type a sentence. Get cinema.",
    blurb: "A product reel: kinetic type, chrome 3D, a prompt turning into ops, a chart that draws itself.",
    tags: ["Kinetic type", "3D", "Chart"],
    make: load(typeASentence, "Type a sentence"),
  },
  {
    id: "solstice",
    title: "Solstice",
    blurb: "A festival promo: aurora sky, a sun machine, a frosted-glass ticket and a daylight counter.",
    tags: ["Procedural sky", "Glass UI", "Counter"],
    make: load(solstice, "Solstice festival promo"),
  },
];
